### ISSUE TITLE
Support interop with other call adapters

### ISSUE THREAD

**Issue by ZacSweers** [slackhq/EitherNet#14]
My sense was that this should Just Work™️ with other adapters, but upon further inspection we seem to be running up against a Java reflection limitation with regard to nested generic return types.

```java
public Single<ApiResult<String, String>> foo();
```

Retrofit only passes on an `ApiResult` class and not the full `ApiResult<String, String>` type. Upon further digging, this seems to be coming from Java itself - the `Method.getGenericReturnType()` returns a `Single<ApiResult>`.

Not sure we can really work around this, will dig around a bit. I suspect a proper fix, if any, would require fixing in Retrofit itself.

**Comment by ZacSweers** [comment]
The workaround for now would be to use the [coroutines-rxjava interop library](https://github.com/Kotlin/kotlinx.coroutines/tree/master/reactive/kotlinx-coroutines-rx3)

```kotlin
interface PandaApi {
  @GET("/")
  suspend fun getPandas(): ApiResult<Pandas, Nothing>
}

// Use rxSingle
rxSingle { pandaApi.getPandas() }
  .subscribe { result -> ... }
```

**Comment by simtse** [comment]
Oh interesting, so right now, if we wanted to use `ApiResult<T, E>` we can't use RxJava right away. Our best bet for async calls for a codebase that uses Rx would be to use coroutines adapter and then interop with Rxjava in order to work with existing Rx chains?

**Comment by ZacSweers** [comment]
Yup seems so. In principle it works but in testing it seems this is a java limitation

**Comment by ZacSweers** [comment]
I have an idea for this: we could use Retrofit's `@Tag` annotation to receive a custom `ResultHint` that in turn holds a `ResultType` instance. We can then look for this hint and use it as an override.

```kotlin
@GET("/")
fun anRxEndpoint(@Tag resultHint: ResultHint): Single<ApiResult<SuccessType, FailureType>>
```

It's annoyingly not type-safe though, but we could maybe we could encourage something like this

```kotlin
@GET("/")
fun anRxEndpoint(@Tag resultHint: ResultHint = ResultHint.create<SuccessType, FailureType>()): Single<ApiResult<SuccessType, FailureType>>
```

So then callers don't have to implement it themselves

**Comment by ZacSweers** [comment]
Another, possibly better alternative would be to see if we can read the full generic type from metadata annotations on the class. We'd have to step out of retrofit's standard API and incur the metadata parsing cost, but we could make it opt-in maybe?

**Comment by ZacSweers** [comment]
I'm going to close this as infeasible for now
