### ISSUE TITLE
[BUG] EitherNet + MultiDex + minSDK 19

### ISSUE THREAD

**Issue by renaudmathieu** [slackhq/EitherNet#18]
### Describe the bug

StackOverflowError during `assembleDebug` with minSDK 19 and `multiDexEnabled true`

```groovy
AGPBI: {"kind":"error","text":"java.lang.StackOverflowError","sources":[{}],"tool":"D8"}
java.lang.StackOverflowError
```

No issue when setting min SDK to 21.

### Requirements (place an `x` in each of the `[ ]`)**
* [x] I've read and understood the [Contributing guidelines](../CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### To Reproduce

- Set minSDK to 19
- Add EitherNet library
- Enable multidex
- run `./gradlew app:assembleDebug`

### Expected behavior

Compilation works as expected.

#### Reproducible in:

https://gist.github.com/renaudmathieu/b1c7deb835b3a4590b30cc5183bbf47d

OS version(s): 

#### Additional context

- No issue when setting min SDK to 21.
- Android Studio 4.1
- gradle-6.5-all

**Comment by ZacSweers** [comment]
This isn't an Eithernet issue but rather an issue with D8. You'll need to file on its issue tracker. 

https://issuetracker.google.com/issues/new?component=317603
