### ISSUE TITLE
[BUG] Exception when looking for an annotation that doesn't exist

### ISSUE THREAD

**Issue by flavioarfaria** [slackhq/EitherNet#50]
### Describe the bug

When the target annotation is missing, we get an exception trying to access an array position that is out of bounds at line 84.

https://github.com/slackhq/EitherNet/blob/5d1c8ec064ab4e9d645b394e3bd07364bbe8001a/src/main/java/com/slack/eithernet/Annotations.kt#L73-L95

The reason is because `nextAnnotations` is smaller than the original array by 1 and the loop code is optimistic about finding the target annotation in the original array. When this doesn't happen, the executed code path merely tries to copy the original array into `nextAnnotations`, overflowing it at the end.

### Requirements (place an `x` in each of the `[ ]`)**
* [x] I've read and understood the [Contributing guidelines](../CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### To Reproduce

1. Write your own `Converter.Factory` and plug it to Retrofit after `ApiResultConverterFactory`;
2. Call `annotations.statusCode()` inside `responseBodyConverter()`;
3. Get the exception thrown.

### Expected behavior

Instead of getting an exception, we should either get:
* `null to (theseAnnotations as Array<Annotation>)` which means we couldn't single out the target annotation (preferable IMO);
* Simply `null`.

#### Reproducible in:

Project version: 1.2.1

OS version(s): Any

#### Additional context

If this is recognized as a bug, I'm happy to push a PR for review.

**Comment by ZacSweers** [comment]
Seems reasonable to me if you wanna send a PR!
