### ISSUE TITLE
[FEATURE] Support declarative error model binding

### ISSUE THREAD

**Issue by flavioarfaria** [slackhq/EitherNet#53]
### Description

At @tonalfitness, we use microservices. Many endpoints across different services use HTTP error codes with meaningful bodies. Turns out the body for a given status code might be totally different for two endpoints. Because of that, the advice provided [here](https://github.com/slackhq/EitherNet#decoding-error-bodies) doesn't really work for us because the status code itself is not enough to know what type to return.

Here's what would be great:

```kotlin
interface MyApi {
    @DecodeErrorBody
    @POST("/some/path")
    suspend fun someEndpoint(): ApiResult<SuccessModel, GenericErrorModel>
}
```

```kotlin
sealed class GenericErrorModel {
    @HttpError(400, 403)
    @JsonClass(generateAdapter = true)
    data class SpecificErrorModel1(
        @Json(name = "intProperty") val intProperty: Int,
    ) : GenericErrorModel()

    @HttpError(500)
    @JsonClass(generateAdapter = true)
    data class SpecificErrorModel2(
        @Json(name = "stringArrayProperty") val stringProperty: String,
        @Json(name = "booleanProperty") val booleanProperty: Boolean,
    ) : GenericErrorModel()
}
```

The approach above is possible by extracting the response type inside a custom converter factory and then checking for a potential sealed error type. The actual response status code could be matched against annotated subtypes to figure out what model to deserialize the response to.

Correctness—like forgetting to annotate a subtype, or having more than one subtype bound to the same status code—could be enforced at compile time if either code generation or reflection is used (with a lint rule in this case).

Not sure if this is a too specific use case of if it's something that also makes sense to a broader audience that uses EitherNet.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](../CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by ZacSweers** [comment]
Sorry I dropped the ball on responding to this. I think what you're describing makes sense, but it's more or less out of the hands of EitherNet and something that would live in your JSON layer. Once you have the `@StatusCode` annotation retrieved in the converter body, I would suggest map that to your desired model. With Moshi you can do that a few different ways. I would suggest doing something like this

- Create a wrapping `@JsonQualifier` annotation that holds the `StatusCode` annotation and forward it in your converter to moshi. You can make this delegate to the real `MoshiConverterFactory`

```kotlin
@JsonQualifier annotation class StatusCodeQualifier(val statusCode: StatusCode)

class StatusCodeForwardingAdapter : Converter.Factory() {
  // In your own converter factory.
  override fun responseBodyConverter(
      type: Type,
      annotations: Array<out Annotation>,
      retrofit: Retrofit
  ): Converter<ResponseBody, *>? {
    val (statusCode, nextAnnotations) = annotations.statusCode() ?: return null
    val statusCodeQualifier = StatusCodeQualifier(statusCode)
    val finalAnnotations = nextAnnotations + statusCodeQualifier
    // type is GenericErrorModel
    // At runtime, delegate to the real MoshiConverterFactory with our extra qualifier.
    // MoshiConverterFactory will fish out the StatusCodeQualifier because it's a JsonQualifier
    return retrofit.nextResponseBodyConverter<Any>(this, type, finalAnnotations)
  }
}
```

Then you need a Moshi adapter factory that looks for this qualifier and decodes accordingly. This is an example of one

```kotlin
class GenericErrorModelAdapterFactory : JsonAdapter.Factory {
  override fun create(type: Type, annotations: Set<Annotation>, moshi: Moshi): JsonAdapter<*>? {
    when (type) {
      GenericErrorModel::class.java -> {
        val statusCodeQualifier = annotations.filterIsInstance<StatusCodeQualifier>().single()
        val nextAnnotations = annotations.nextAnnotations<StatusCodeQualifier>()
        return moshi.adapter<Any>(
            CODE_MAPPINGS.getValue(statusCodeQualifier.statusCode.value), nextAnnotations)
      }
      else -> return null
    }
  }

  private companion object {
    // Simple bit of kotlin reflection to map codes to classes, implement this however you wish
    val CODE_MAPPINGS = buildMap {
      GenericErrorModel::class.sealedSubclasses.forEach { subclass ->
        for (code in subclass.findAnnotation<HttpError>()!!.codes) {
          put(code, subclass.java)
        }
      }
    }
  }
}
```

**Comment by flavioarfaria** [comment]
Thanks for your response @ZacSweers. This is what we ended up doing back then, I just thought this could be considered as a feature of the library, but it looks like it might be too specific.
