### ISSUE TITLE
(how) should we handle error bodies in 4xx responses?

### ISSUE THREAD

**Issue by ZacSweers** [slackhq/EitherNet#6]
Does this fit in `ApiFailure` or `HttpFailure` somewhere?

Some ideas:

### A. Reuse ApiFailure

In this event, upon 4xx responses we would attempt to request a delegate converter to decode the error body and report in an ApiFailure with a code.

Awkward because it combines ApiFailure and HttpFailure

### B. Add an error to HttpFailure

Simple, but potentially awkward because we then add a type to HttpFailure too. If we do this, I think we should reuse the same error type as ApiError

## Other questions

- How do we enable this?
  - parameter to the call adapter factory?
  - `@DecodeErrorBody` opt-in annotation?
- What if there are multiple error types? Some APIs return different errors for different status codes
  - Could we pass the error code via annotation in the converter lookup, similar to how we use `@ResultType`

**Comment by ZacSweers** [comment]
I'm leaning toward B right now + `@StatusCode` annotation passed via annotation

**Comment by steventannz** [comment]
Things to consider:

In the case of B, should this be automatically enabled? 

If so, in the event of a polymorphic 200 being used, the 400's body may potentially not match as the same error type is being reused and the attempt to serialize will fail.

Could potentially catch this and return as an UnknownFailure if serialization fails. However, could be misleading if the only thing someone cared about was the HttpException + status code, but was now being reported as an UnknownFailure.

**Comment by ZacSweers** [comment]
Yup. I'm thinking we should start this with an opt-in annotation for now
